//
//  Headers.swift
//  HairSwap
//
//  Created by  Kostantin Zarubin on 23/11/2018.
//  Copyright © 2018  Kostantin Zarubin. All rights reserved.
//

import Foundation

class Content {
    static let headers = ["Black hair", "Brown hair", "Red Hair","Grey hair", "Ginger hair", "Blond hair", "Burgundy Hair", "White hair", "Blue hair","Green hair"]
    static let images = [
        ["0", "1", "2"],
        ["3", "4", "5"],
        ["6", "7", "8"],
        ["9", "10", "11"],
        ["12", "13", "14"],
        ["15", "16", "17"],
        ["18", "19", "20"],
        ["21", "22", "23"],
        ["24", "25", "26"],
        ["27", "28", "29"]
    ]
    static let titles = [
        ["Blue Black Hair", "Long, luscious and Sulty", "Long, Tousled Layers"],
        ["Deep Dark Brown Hair", "Long and Layered Browns", "Warm Medium Tones"],
        ["Mohawk on Pink Red Hair", "Crimson Red Hair", "Very Short Dyed Red Hair"],
        ["Dance Floor Ready", "Curly Pixie", "Tight Silver Curls"],
        ["Bright Poppy", "CINNAMON", "Ligh auburn"],
        ["All-Over Cool Blonde", "Dark Dishwater Blonde", "Golden Bronze Blonde"],
        ["Classic Plum", "Dark Brown Plum", "Deep Red Plum"],
        ["Cold blond", "Platinum", "Lunar White"],
        ["Deep Blue Bob", "Teal Tresses", "Ocean-Colored Ombre"],
        ["GREEN ENVY", "Green Mermaid", "Lustrous Green"]
    ]
    
    static let text = [
        ["Are you aiming for dark and sultry, but with a cool edge? If so, then this is the look for you! Subtle and chic, this hair color will take you from the office to the party and have you looking totally fab for both occasions. It transforms in different lighting, and the deep dark color leaves your hair with great depth and shine. To achieve this look, search for a dark blue black color that will give a high gloss. We also recommend treating your hair prior to coloring so it’s super smooth and ready to rock the new shade!", "Want to inject some color? Blue highlights are the way to do it! We recommend pairing them with a deep blue black hair color as the base, so they really pop. Or alternatively, add the highlights to your natural color to simply rejuvenate your look. These are often great for a bit of fun as the brightness will fade after a few washes, but they also pack a real punch and make a real statement. These colored blue highlights work particularly well in layered hair, adding texture, interest and fullness to the style.", "If you like to make a statement with your hair, this is the one for you! An all over blue black hair dye will really make people do a double take and say ‘Wow’. Play around with colors and see what works for your skin tone and style. Fairer skin often works better using more of a purple blue, whereas darker, more olive complexions can take a deep cooler blue. This all-over color works best on short, cropped styles for a really vivid color pop to lift your look."],
        ["Victoria’s Secret angel Adriana Lima dyes her slightly wavy hair in a dark brown hue to accentuate her tanned skin and bright blue eyes. This color makes her hair look thicker and adds it extra brilliance. Remember to use special care products for dyed hair to maintain the freshness and saturation of your hair color.", "Great color for those with brown hair on the darker side, some medium brown balayage that gradually becomes golden is a natural look for you! It’s great for a pop of color without heaving to heavily dye your tresses to reach a golden hue.", "A sultry take on natural golden brown hair, opting for auburn or warm tones works well on warm-toned skin girls or even fair-skinned with green eyes (to bring out that dreamy color!). The base of the hair has been dyed to match the highlights in tone for a seamless color melt!"],
        ["Nothing is edgier than a short shaved-up mohawk, except maybe this particular pink-red shaved-up mohawk! Trim the hair along both sides of the head and keep the center section long so you have some versatility in styling. Add pink red hair color for the long section, and you will be a full-blown punk.", "Even the brightest style, as this crimson red hair, can be very classy when styled and accessorized correctly. Try a thick, braided crown topped off with a jeweled headband. You will be one fancy lady.", "Who says curly hair can’t go super short? Keep those curls under control by chopping them into a pixie cut and adding some bright shading to make them pop. Short dyed red hair always looks sexy and feminine, so be ready to get compliments!"],
        ["Loose waves add a visually intriguing dimension to gray tresses. The grey hair trend looks exceptionally fabulous on lengthier locks. The waves create an interactive light and dark contrast that changes according to lighting and movement of the hair. So dance the night away, everyone is watching.", "Give the newest trend a run for its money and have your trusted stylist assist you in pulling this off. Or better still, set the style overnight and go to bed with some rollers. Who says going full grandma cannot be pulled off?", "Achieve this ethereal look by curling your granny hair only at the ends. Shape tight ringlets with a flat iron, spriz with hair spray and tousle the curls slightly for a fluffy look that still holds the tight curl."],
        ["For the most Mad Men of aspiring redheads, a striking shade of ruby like Christina Hendricks' iconic Joan Holloway dye job is the way to go. Just be sure to maintain it with a color-saving shampoo!", "This brownish-red color is perfectly cool and a very understated choice if you’re not looking to make a dramatic change to your hair.", "When you think of red hair, light auburn might be the shade that first comes to mind. This color looks best when paired with fair skin and light eye colors."],
        ["If you want to go on the cooler side, try an all-over light, silvery, cool blonde that is a refreshing take on the classic honey blonde. This neutral, pearly tone compliments cooler skin tones.", "This dark dishwater blonde hair is more brunette than blonde. This may be an ideal hair color for those in the process of growing out their natural hair to blend existing, grown-out highlights.", "This has an ombre effect with dark bronze-colored roots, melded together in the middle, seamlessly blending into a lighter golden blonde."],
        ["The classic plum color is great for everyone, but it suits blue or hazel eyes best — warm-toned skin can pull this style off as well!", "This dark plum hair is perfect if your hair is already brown. Add plum with warmer undertones for a perfect plum update.", "A beautiful contrast for fair skin is a deep plum color with red hue. If you have green eyes, then ask your stylist for this lovely shade."],
        ["Minimize washing. Your hair is going to be pretty dry after such a drastic process, and the less you was it the better. You'll get by, and your hair will thank you for it! I have bleached hair (though not white anymore), and I shampoo it maybe once a week. If it starts feeling greasy, I'll throw in some corn starch as a dry shampoo. Use purple shampoo. When you do shampoo, you're going to want something that will keep your tone fresh. That's where purple shampoo comes in! Generic (that's the brand name) has an inexpensive purple shampoo available at Sally's. Keep the coconut oil handy. Like I said, bleaching is drying. Coconut oil works wonders to keep your hair smooth, soft, shiny, and packed full of nutrients. Apply to ends and after washes.", "The trick to achieving most colours is in the initial bleaching. You’ll need to give your hair an overall bleach before you can then reintroduce a colour of your choosing. Remember, if you’re going for something quite different to your natural colour it’ll require a lot of maintenance – so be sure to have the budget/tools at your disposal.", "Lunar White is a non-damaging purple based toner designed to eliminate blonde or yellow tones from hair, leaving you with a luscious platinum white. Hair toner works best on pale yellow hair tones and does not work well on brassy yellows or oranges. Using a toner is always recommend before using a pastel hair color to create a blank slate for more accurate color."],
        ["If a bold blue bob hasn’t made it onto your hair bucket list yet, add it immediately. An angular, chin-length cut tinged with blue is a perfect look for a trend-setting fashionista. Styling tip: Curl the strands of your bob mid-shaft to ends with a curling iron and loosen the curls with your fingers for a messy-but-fabulous style.", "Dark blue ombre hair doesn’t need to be so, well, dark. Try a deep teal balayage and channel your inner mermaid. Oh, the best part about this look? It’s low-maintenance and requires little to no touching up.", "The ombre look continues to reinvent itself, and now it’s taken on a beautiful blue shade. The vivid pastel blue ombre is the ultimate “cool girl” look, guaranteed to turn heads."],
        ["For best results apply to hair that has been pre-lightened to pale blonde. Do not mix with peroxide. Shampoo hair using a deep cleansing shampoo. Apply to freshly washed, dry hair. Apply evenly using a tint brush and comb through until frothy. Cover your hair with a plastic cap and leave for 30 minutes. You can apply heat to intensify the process. Rinse with cold water, away from your face.", "Top tips: For blue or pastel shades, hair will need to be very light blonde, so pre-lighten if you’ve not been blessed with this colour. If you’re creating a pastel shade, the colour you pre-mix is a good indicator of the colour result - if you want a more vibrant shade, just add more colour cream. Semi-permanent shades are ideal for maintaining colour vibrancy between permanent applications. Remember, if your hair’s previously coloured, this may affect results. Avoid staining your fav jumper by having an old towel at the ready and use some skin barrier cream around your hairline/ears. Have some cotton pads and skin toner handy just in case you get some product on your skin. If you’re lucky enough to have thick locks or hair longer than shoulder length, you’ll need two or more packs for a nice, even coverage", "Dark green hair dye can still be used in such a way that can add shine. I am sure; your friends will then be super jealous your hair luster. Also, I can guarantee, this will be the green hair dye you will not want to get rid."]
    ]
    
}
